/**
 * test/Test.java - lab3
 * An abstract class describing a runnable test.
 */

package test.util;

public abstract class Test {
    private String name;
    private static int passed, attempted;
    private final static TimeoutHandler timeout = new TimeoutHandler(3000);

    /**
     * Runs the assertions for this test. The assertion
     * of 'does not throw' is automatically wrapped over
     * the test.
     * @param end a runnable that should be called at the end of a test
     */
    public abstract void test(Runnable end) throws Throwable;

    /**
     * Sets the span of the timeout handler.
     * @param timeout the span of the timeout given in milliseconds
     */
    protected void setTimeout(long timeout) {
        this.timeout.setTimeout(timeout);
    }

    /**
     * Tests if two values are equal. Passes the assertion
     * if the values are equal, otherwise fails.
     * @param expected the value that is expected from the test
     * @param given the value that was generated by the test
     * @param message a string explaining the assertion to the user
     */
    public static <T> void equal(T given, T expected, String message) {
        boolean success = expected.equals(given);
        timeout.reset();

        // writes the assertion in red upon failure,
        // and green upon success. a checkmark preceeds the
        // success message and an x preceeds a failed message
        System.out.format(
            " \u001b[%dm%s %s%s\u001b[39m\n",
            success ? 32 : 31,
            success ? "\u2713" : "x",
            message,
            !success ? " (expected " + expected + ", got " + given + ")" : ""
        );

        // talls the number of assertions run by this test
        attempted += 1;
        passed += success ? 1 : 0;
    }

    /**
     * Runs the test and measures success rate.
     */
    public void run(final TestEnd next) {
        final Test that = this;
        final FBool failed = new FBool();

        try {
            System.out.format("\n\u001b[36m%s\u001b[39m\n\n", this.name);
            timeout.onFail(new Runnable() {
                public void run() {
                    timeout.stop();
                    failed.set(true);
                    System.out.println("\n \u001b[31mTest timed out.\u001b[39m");
                    next.run(false);
                }
            });
            timeout.start();

            this.test(new Runnable() {
                public void run() {
                    if (!failed.state()) {
                        timeout.stop();
                        System.out.println();
                        System.out.format(" \u001b[36m%d/%d assertions passed\u001b[39m\n", that.passed, that.attempted);
                        next.run(that.passed == that.attempted);
                    }
                }
            });
        } catch (Throwable th) {
            timeout.stop();
            this.attempted += 1;
            th.printStackTrace();
            System.out.format("\n \u001b[31mTest threw exception: %s\u001b[39m\n", th.getMessage());
            System.out.format(" \u001b[36m%d/%d assertions passed\u001b[39m\n", this.passed, this.attempted);
        }
    }

    /**
     * Creates a new test with a given name.
     */
    public Test(String testName) {
        this.passed = 0;
        this.attempted = 0;
        this.name = testName;
    }
}
